### PR TITLE
feat: new pumps data

### PR DESCRIPTION
**Pull request by dnsos**
This PR includes the newly gathered pumps data (by @Lisa-Stubert) in the map. The dataset contains more pumps than the previously used one and originates from the Geoportal Berlin.

The PR:
- adds the new pumps file
- includes the new data source in the sidebar (sources & FAQ)

(This seems to also be related to #170)

### CODE REVIEW

**Comment by fabianmoronzirfas** [comment]
@Lisa-Stubert how did you get the data? Is there something we can run on a weekly basis that aggregates that data?

**Comment by Lisa-Stubert** [comment]
> @Lisa-Stubert how did you get the data? Is there something we can run on a weekly basis that aggregates that data?

The data comes via a WFS service and must then be post-processed. We can script that, but I'm not sure it's worth it at this point, because the data set is only updated when a pump is built or removed, which shouldn't happen very often. We are still considering how we can get reliable data in the future about which pumps are functional and which are not. If we are receiving such data, a script might make sense.

**Comment by dnsos** [comment]
Since scripting the pump data at this moment does not seem to make sense, I will go ahead and merge this.

**Comment by fabianmoronzirfas** [comment]
@Lisa-Stubert thanks. Could still share your pipeline for getting that data? Maybe as a script with a README in a separate folder called `/tools/pumps` in this repo. So we don't loose any information.

**Comment by fabianmoronzirfas** [comment]
Just a follow up on this. @Lisa-Stubert Did you see the issue #170 ? Is this something we could incorporate into your script?

**Pull request merged**
